




```{r}

library(reprex)
library(styler)
library(tidymodels)
library(dotwhisker)



```



```{r, style = TRUE}

urchins <-
  read_csv("https://tidymodels.org/start/models/urchins.csv") %>% 
  setNames(c("food_regime", "initial_volume", "width")) %>% 
  mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))


```



```{r}

ggplot(urchins,
       aes(x = initial_volume, 
           y = width, 
           group = food_regime, 
           col = food_regime)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) +
  scale_color_viridis_d(option = "plasma", end = .7)


```





```{r}

lm_mod <- linear_reg() 

lm_fit <- 
  lm_mod %>% 
  fit(width ~ initial_volume * food_regime, data = urchins)


lm_fit




```
```{r}
tidy(lm_fit) 
```


```{r}

tidy(lm_fit) %>% 
  dwplot(dot_args = list(size = 2, color = "black"),
         whisker_args = list(color = "black"),
         vline = geom_vline(xintercept = 0, colour = "grey50", linetype = 2))

```




# Predict


```{r}

new_points <- expand.grid(initial_volume = 20, 
                          food_regime = c("Initial", "Low", "High"))
new_points





new_points <- expand.grid(initial_volume = c(0,20) , food_regime = c("Initial", "Low", "High"))

new_points


```





```{r}

mean_pred <- predict(lm_fit, new_data = new_points)

conf_int_pred <- predict(lm_fit, 
                         new_data = new_points, 
                         type = "conf_int")


plot_data <- 
  new_points %>% 
  bind_cols(mean_pred) %>% 
  bind_cols(conf_int_pred)



# and plot:
ggplot(plot_data, aes(x = food_regime)) + 
  geom_point(aes(y = .pred)) + 
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) + 
  labs(y = "urchin size")


```






# NY Flights


```{r}

library(tidymodels)   
library(nycflights13)  
library(skimr)  


set.seed(123)

flight_data <- 
  flights %>% 
  mutate(
    arr_delay = ifelse(arr_delay >= 30, "late", "on_time"),
    arr_delay = factor(arr_delay),
    date = lubridate::as_date(time_hour)
  ) %>% 
  inner_join(weather, by = c("origin", "time_hour")) %>% 
  select(dep_time, flight, origin, dest, air_time, distance, 
         carrier, date, arr_delay, time_hour) %>% 
  na.omit() %>% 
  mutate_if(is.character, as.factor)


```



```{r}
flight_data %>% 
  count(arr_delay) %>% 
  mutate(prop = n/sum(n))



```



```{r}
flight_data %>% 
  skimr::skim(dest, carrier) 
```





```{r}

flight_data %>% skimr::skim() 


```






```{r}

# Fix the random numbers by setting the seed 
# This enables the analysis to be reproducible when random numbers are used 
set.seed(222)
# Put 3/4 of the data into the training set 
data_split <- initial_split(flight_data, prop = 3/4)

# Create data frames for the two sets:
train_data <- training(data_split)
test_data  <- testing(data_split)


```







```{r}

flights_rec <- 
  recipe(arr_delay ~ ., data = train_data) 


```







```{r}

flights_rec <- 
  recipe(arr_delay ~ ., data = train_data) %>% 
  update_role(flight, time_hour, new_role = "ID") 


```



```{r}

flight_data %>% 
  distinct(date) %>% 
  mutate(numeric_date = as.numeric(date)) 

```





# create feature

```{r}

flights_rec <- 
  recipe(arr_delay ~ ., data = train_data) %>% 
  update_role(flight, time_hour, new_role = "ID") %>% 
  step_date(date, features = c("dow", "month")) %>%               
  step_holiday(date, 
               holidays = timeDate::listHolidays("US"), 
               keep_original_cols = FALSE) %>% 
  step_dummy(all_nominal_predictors())


```






# fitting a model with a recipe


```{r}

lr_mod <- 
  logistic_reg() %>% 
  set_engine("glm")

flights_wflow <- 
  workflow() %>% 
  add_model(lr_mod) %>% 
  add_recipe(flights_rec)

flights_wflow

```





```{r}


flights_fit <- 
  flights_wflow %>% 
  fit(data = train_data)


```







```{r}

flights_fit %>% 
  extract_fit_parsnip() %>% 
  tidy()


```



```{r}

predict(flights_fit, test_data)

```




